In [2]:
import numpy as np
import timeit

In [3]:
a=[1,"v",4,5,3.4]

In [5]:
a[1]

'v'

In [6]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x.dtype

dtype('int64')

In [8]:
x.shape

(10,)

In [9]:
x=np.arange(16).reshape(4,4)

In [10]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
y=x

In [12]:
x[1,1]=999

In [13]:
y

array([[  0,   1,   2,   3],
       [  4, 999,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [14]:
z=x+0

In [15]:
x[1,1]=7

In [16]:
x

array([[ 0,  1,  2,  3],
       [ 4,  7,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
y

array([[ 0,  1,  2,  3],
       [ 4,  7,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
z

array([[  0,   1,   2,   3],
       [  4, 999,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [19]:
np.array([3.3,3.4]).dtype

dtype('float64')

In [20]:
np.array("hola que tal").dtype

dtype('<U12')

In [21]:
np.array(list("hola que tal")).dtype

dtype('<U1')

In [22]:
np.array(list("hola que tal")).shape

(12,)

In [23]:
np.array([True,True]).dtype

dtype('bool')

In [26]:
np.array([3,5,1,2**65]).dtype

dtype('O')

In [28]:
2**65

36893488147419103232

In [29]:
#from math import sin
from numpy import sin, pi

In [30]:
np.sin(3)

0.1411200080598672

In [31]:
sin(3)

0.1411200080598672

In [35]:
#comprehension
for i in ( n* 2 * pi / 360 for n in range (0,91,10) ):print(i)

0.0
0.17453292519943295
0.3490658503988659
0.5235987755982988
0.6981317007977318
0.8726646259971648
1.0471975511965976
1.2217304763960306
1.3962634015954636
1.5707963267948966


In [36]:
for i in [ n* 2 * pi / 360 for n in range (0,91,10) ]:print(i)

0.0
0.17453292519943295
0.3490658503988659
0.5235987755982988
0.6981317007977318
0.8726646259971648
1.0471975511965976
1.2217304763960306
1.3962634015954636
1.5707963267948966


In [37]:
x=[ n* 2 * pi / 360 for n in range (0,91,10) ]

In [40]:
np.sin(x)

array([0.        , 0.17364818, 0.34202014, 0.5       , 0.64278761,
       0.76604444, 0.8660254 , 0.93969262, 0.98480775, 1.        ])

In [39]:
import math
math.sin(x)

TypeError: must be real number, not list

In [41]:
[math.sin(i) for i in x]

[0.0,
 0.17364817766693033,
 0.3420201433256687,
 0.49999999999999994,
 0.6427876096865393,
 0.766044443118978,
 0.8660254037844386,
 0.9396926207859083,
 0.984807753012208,
 1.0]

In [42]:
y=np.array(x)

In [47]:
def gradosSin(n):
    return np.sin(n*2*pi/360)

In [49]:
x=np.linspace(0,90,3)
x

array([ 0., 45., 90.])

In [50]:
gradosSin(x)

array([0.        , 0.70710678, 1.        ])

In [53]:
%%timeit
gradosSin(np.linspace(0,90,10))

102 µs ± 4.42 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [54]:
!ls

codigoAvanzado.ipynb  imports		      numpy.ipynb   Untitled.ipynb
codigoBasico.ipynb    integracionScipy.ipynb  pandas.ipynb
display.ipynb	      intel.ipynb	      __pycache__
ficheros.ipynb	      latticeNumpy.ipynb      scipy.ipynb


In [56]:
%%timeit
(gradosSin(n) for n in range(0,91,10) )


609 ns ± 1.02 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [57]:
%%timeit
[gradosSin(n) for n in range(0,91,10) ]

26.5 µs ± 888 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [58]:
%%timeit
np.fromiter((gradosSin(n) for n in range(0,91,10) ), dtype=float)

33 µs ± 464 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [60]:
%%timeit
gradosSin(np.linspace(0,9000,9000)/100)

404 µs ± 742 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [61]:
%%timeit
[gradosSin(n/100) for n in range(0,9000,1) ]

22.8 ms ± 1.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [62]:
a=list(range(100))

In [64]:
np.array(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [65]:
a[3:10]

[3, 4, 5, 6, 7, 8, 9]

In [66]:
a[90:-3]

[90, 91, 92, 93, 94, 95, 96]

In [68]:
a[3:10:2] #inicio, fin, paso

[3, 5, 7, 9]

In [71]:
np.array(a[::6])

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [72]:
board=np.zeros((8,8), dtype=int)
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [73]:
board[0::2,1::2]=1
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [74]:
board[1::2,0::2]=1
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [75]:
board[3]

array([1, 0, 1, 0, 1, 0, 1, 0])

In [77]:
board[:,3]=7

In [78]:
board

array([[0, 1, 0, 7, 0, 1, 0, 1],
       [1, 0, 1, 7, 1, 0, 1, 0],
       [0, 1, 0, 7, 0, 1, 0, 1],
       [1, 0, 1, 7, 1, 0, 1, 0],
       [0, 1, 0, 7, 0, 1, 0, 1],
       [1, 0, 1, 7, 1, 0, 1, 0],
       [0, 1, 0, 7, 0, 1, 0, 1],
       [1, 0, 1, 7, 1, 0, 1, 0]])

In [79]:
board[:,0]=board[:,3]+board[:,7]

In [80]:
board

array([[8, 1, 0, 7, 0, 1, 0, 1],
       [7, 0, 1, 7, 1, 0, 1, 0],
       [8, 1, 0, 7, 0, 1, 0, 1],
       [7, 0, 1, 7, 1, 0, 1, 0],
       [8, 1, 0, 7, 0, 1, 0, 1],
       [7, 0, 1, 7, 1, 0, 1, 0],
       [8, 1, 0, 7, 0, 1, 0, 1],
       [7, 0, 1, 7, 1, 0, 1, 0]])

In [81]:
gastos=board[:,3]

In [83]:
gastos

array([7, 7, 7, 7, 7, 7, 7, 7])

In [84]:
gastos.shape

(8,)

In [85]:
np.dot(board,gastos)

array([126, 119, 126, 119, 126, 119, 126, 119])

In [86]:
board @ gastos

array([126, 119, 126, 119, 126, 119, 126, 119])

In [87]:
#broadcasting

In [88]:
4+[3,4,2]

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [90]:
4 + np.array([3,4,2])/10

array([4.3, 4.4, 4.2])

In [92]:
np.array([3,4,5])-np.array([2,2,10])

array([ 1,  2, -5])

In [95]:
np.array([1,2])+np.zeros((2,2),dtype=int)

array([[1, 2],
       [1, 2]])

In [97]:
np.array([[1],[2]])+np.zeros((2,2),dtype=int)

array([[1, 1],
       [2, 2]])

In [98]:
np.array([[1,2]])+np.zeros((2,2),dtype=int)

array([[1, 2],
       [1, 2]])

In [99]:
np.array([[1,2]]).shape

(1, 2)

In [100]:
np.array([[1],[2]]).shape

(2, 1)

In [101]:
np.array([[1,2]]).T+np.zeros((2,2),dtype=int)

array([[1, 1],
       [2, 2]])

In [102]:
np.array([[1,2]])+np.zeros((2,2),dtype=int)

array([[1, 2],
       [1, 2]])

In [103]:
np.array([[1,2]]).shape

(1, 2)

In [104]:
np.zeros((2,2),dtype=int).shape

(2, 2)