In [1]:
import pandas as pd

In [2]:
s=pd.DataFrame( {"area": pd.Series([3,4,5,6],index=list("abcd") ), "masa":pd.Series([3,5.4,2.2,1.2],index=list("acdf"))}) 
s

area  masa
a   3.0   3.0
b   4.0   NaN
c   5.0   5.4
d   6.0   2.2
f   NaN   1.2

In [47]:
#el apply es importante en general. En otros lenguajes es map
x=pd.concat([s,s.apply(lambda x: x*x)],axis=1)
x

area  masa  area   masa
a   3.0   3.0   9.0   9.00
b   4.0   NaN  16.0    NaN
c   5.0   5.4  25.0  29.16
d   6.0   2.2  36.0   4.84
f   NaN   1.2   NaN   1.44

In [31]:
y=pd.concat([s,s.apply(lambda x: x*x)],keys=["normal","cuadrado"],names=["tipo","medida"],axis=1)
y

tipo   normal      cuadrado       
medida   area masa     area   masa
a         3.0  3.0      9.0   9.00
b         4.0  NaN     16.0    NaN
c         5.0  5.4     25.0  29.16
d         6.0  2.2     36.0   4.84
f         NaN  1.2      NaN   1.44

In [48]:
c=x.columns.to_frame()
c.insert(0,"tipo","norm,norm,cuad,cuad".split(","))
print(c)
nuevo=pd.MultiIndex.from_frame(c)
nuevo

      tipo     0
area  norm  area
masa  norm  masa
area  cuad  area
masa  cuad  masa


MultiIndex([('norm', 'area'),
            ('norm', 'masa'),
            ('cuad', 'area'),
            ('cuad', 'masa')],
           names=['tipo', 0])

In [49]:
x.columns=nuevo
x

tipo norm       cuad       
0    area masa  area   masa
a     3.0  3.0   9.0   9.00
b     4.0  NaN  16.0    NaN
c     5.0  5.4  25.0  29.16
d     6.0  2.2  36.0   4.84
f     NaN  1.2   NaN   1.44

In [50]:
x=pd.concat([s,s.apply(lambda x: x*x)],axis=1)
x

area  masa  area   masa
a   3.0   3.0   9.0   9.00
b   4.0   NaN  16.0    NaN
c   5.0   5.4  25.0  29.16
d   6.0   2.2  36.0   4.84
f   NaN   1.2   NaN   1.44

In [78]:
z=pd.concat( [ x.iloc[:,[0,1]],x.iloc[:,[2,3]]  ],keys=["normal","cuadrado"],axis=1)
z

normal      cuadrado       
    area masa     area   masa
a    3.0  3.0      9.0   9.00
b    4.0  NaN     16.0    NaN
c    5.0  5.4     25.0  29.16
d    6.0  2.2     36.0   4.84
f    NaN  1.2      NaN   1.44

In [65]:
z.loc['a':'c']

normal      cuadrado       
    area masa     area   masa
a    3.0  3.0      9.0   9.00
b    4.0  NaN     16.0    NaN
c    5.0  5.4     25.0  29.16

In [66]:
z['cuadrado'].loc['a':'c']

area   masa
a   9.0   9.00
b  16.0    NaN
c  25.0  29.16

In [67]:
z.median()

normal    area     4.50
          masa     2.60
cuadrado  area    20.50
          masa     6.92
dtype: float64

In [79]:
z['normal']*z["cuadrado"]

area     masa
a   27.0   27.000
b   64.0      NaN
c  125.0  157.464
d  216.0   10.648
f    NaN    1.728

In [80]:
z["cuboarea"]= (z['normal']*z["cuadrado"])["area"]
z

normal      cuadrado        cuboarea
    area masa     area   masa         
a    3.0  3.0      9.0   9.00     27.0
b    4.0  NaN     16.0    NaN     64.0
c    5.0  5.4     25.0  29.16    125.0
d    6.0  2.2     36.0   4.84    216.0
f    NaN  1.2      NaN   1.44      NaN

In [92]:
z=z.join(pd.concat([z['normal']*z["cuadrado"]],keys=["cube"],axis=1))

In [93]:
z

normal      cuadrado        cuboarea   cube         
    area masa     area   masa            area     masa
a    3.0  3.0      9.0   9.00     27.0   27.0   27.000
b    4.0  NaN     16.0    NaN     64.0   64.0      NaN
c    5.0  5.4     25.0  29.16    125.0  125.0  157.464
d    6.0  2.2     36.0   4.84    216.0  216.0   10.648
f    NaN  1.2      NaN   1.44      NaN    NaN    1.728

In [94]:
z[("quad","masa")]= z["cuadrado"]["masa"]**2
z

normal      cuadrado        cuboarea   cube               quad
    area masa     area   masa            area     masa      masa
a    3.0  3.0      9.0   9.00     27.0   27.0   27.000   81.0000
b    4.0  NaN     16.0    NaN     64.0   64.0      NaN       NaN
c    5.0  5.4     25.0  29.16    125.0  125.0  157.464  850.3056
d    6.0  2.2     36.0   4.84    216.0  216.0   10.648   23.4256
f    NaN  1.2      NaN   1.44      NaN    NaN    1.728    2.0736

In [95]:
z.to_numpy()

array([[  3.    ,   3.    ,   9.    ,   9.    ,  27.    ,  27.    ,
         27.    ,  81.    ],
       [  4.    ,      nan,  16.    ,      nan,  64.    ,  64.    ,
             nan,      nan],
       [  5.    ,   5.4   ,  25.    ,  29.16  , 125.    , 125.    ,
        157.464 , 850.3056],
       [  6.    ,   2.2   ,  36.    ,   4.84  , 216.    , 216.    ,
         10.648 ,  23.4256],
       [     nan,   1.2   ,      nan,   1.44  ,      nan,      nan,
          1.728 ,   2.0736]])

In [96]:
z.describe()

normal             cuadrado               cuboarea        cube  \
           area      masa       area       masa                    area   
count  4.000000  4.000000   4.000000   4.000000    4.000000    4.000000   
mean   4.500000  2.950000  21.500000  11.110000  108.000000  108.000000   
std    1.290994  1.791647  11.676187  12.424122   82.563107   82.563107   
min    3.000000  1.200000   9.000000   1.440000   27.000000   27.000000   
25%    3.750000  1.950000  14.250000   3.990000   54.750000   54.750000   
50%    4.500000  2.600000  20.500000   6.920000   94.500000   94.500000   
75%    5.250000  3.600000  27.750000  14.040000  147.750000  147.750000   
max    6.000000  5.400000  36.000000  29.160000  216.000000  216.000000   

                         quad  
             masa        masa  
count    4.000000    4.000000  
mean    49.210000  239.201200  
std     72.924118  408.764323  
min      1.728000    2.073600  
25%      8.418000   18.087600  
50%     18.824000   52.212800  
75%     59.616000  273.326400  
max    157.464000  850.305600

In [97]:
z[ z["cuboarea"] > 20 ]

normal      cuadrado        cuboarea   cube               quad
    area masa     area   masa            area     masa      masa
a    3.0  3.0      9.0   9.00     27.0   27.0   27.000   81.0000
b    4.0  NaN     16.0    NaN     64.0   64.0      NaN       NaN
c    5.0  5.4     25.0  29.16    125.0  125.0  157.464  850.3056
d    6.0  2.2     36.0   4.84    216.0  216.0   10.648   23.4256

In [98]:
#o to_excel, to_hdf, to parquet...
z.to_csv("tmp.csv")
!cat tmp.csv

,normal,normal,cuadrado,cuadrado,cuboarea,cube,cube,quad
,area,masa,area,masa,,area,masa,masa
a,3.0,3.0,9.0,9.0,27.0,27.0,27.0,81.0
b,4.0,,16.0,,64.0,64.0,,
c,5.0,5.4,25.0,29.160000000000004,125.0,125.0,157.46400000000003,850.3056000000003
d,6.0,2.2,36.0,4.840000000000001,216.0,216.0,10.648000000000003,23.425600000000006
f,,1.2,,1.44,,,1.728,2.0736


In [99]:
a=pd.read_csv("tmp.csv")
a

Unnamed: 0 normal normal.1 cuadrado          cuadrado.1  cuboarea   cube  \
0        NaN   area     masa     area                masa       NaN   area   
1          a    3.0      3.0      9.0                 9.0      27.0   27.0   
2          b    4.0      NaN     16.0                 NaN      64.0   64.0   
3          c    5.0      5.4     25.0  29.160000000000004     125.0  125.0   
4          d    6.0      2.2     36.0   4.840000000000001     216.0  216.0   
5          f    NaN      1.2      NaN                1.44       NaN    NaN   

               cube.1                quad  
0                masa                masa  
1                27.0                81.0  
2                 NaN                 NaN  
3  157.46400000000003   850.3056000000003  
4  10.648000000000003  23.425600000000006  
5               1.728              2.0736

In [100]:
z.stack()

cuadrado     cube  cuboarea  normal      quad
a            NaN      NaN      27.0     NaN       NaN
  area      9.00   27.000       NaN     3.0       NaN
  masa      9.00   27.000       NaN     3.0   81.0000
b            NaN      NaN      64.0     NaN       NaN
  area     16.00   64.000       NaN     4.0       NaN
c            NaN      NaN     125.0     NaN       NaN
  area     25.00  125.000       NaN     5.0       NaN
  masa     29.16  157.464       NaN     5.4  850.3056
d            NaN      NaN     216.0     NaN       NaN
  area     36.00  216.000       NaN     6.0       NaN
  masa      4.84   10.648       NaN     2.2   23.4256
f masa      1.44    1.728       NaN     1.2    2.0736

In [104]:
print(z)
#el indice nulo de cuboarea nos genera mas entradas al ir y volver
z.stack().unstack()

  normal      cuadrado        cuboarea   cube               quad
    area masa     area   masa            area     masa      masa
a    3.0  3.0      9.0   9.00     27.0   27.0   27.000   81.0000
b    4.0  NaN     16.0    NaN     64.0   64.0      NaN       NaN
c    5.0  5.4     25.0  29.16    125.0  125.0  157.464  850.3056
d    6.0  2.2     36.0   4.84    216.0  216.0   10.648   23.4256
f    NaN  1.2      NaN   1.44      NaN    NaN    1.728    2.0736


cuadrado              cube                 cuboarea           normal       \
            area   masa        area     masa          area masa        area   
a      NaN   9.0   9.00  NaN   27.0   27.000     27.0  NaN  NaN    NaN  3.0   
b      NaN  16.0    NaN  NaN   64.0      NaN     64.0  NaN  NaN    NaN  4.0   
c      NaN  25.0  29.16  NaN  125.0  157.464    125.0  NaN  NaN    NaN  5.0   
d      NaN  36.0   4.84  NaN  216.0   10.648    216.0  NaN  NaN    NaN  6.0   
f      NaN   NaN   1.44  NaN    NaN    1.728      NaN  NaN  NaN    NaN  NaN   

       quad                 
  masa      area      masa  
a  3.0  NaN  NaN   81.0000  
b  NaN  NaN  NaN       NaN  
c  5.4  NaN  NaN  850.3056  
d  2.2  NaN  NaN   23.4256  
f  1.2  NaN  NaN    2.0736

In [105]:

s = pd.Series(range(15))
d = s.rolling(window=3).sum()
pd.DataFrame({'original':s,'sumado':d})


original  sumado
0          0     NaN
1          1     NaN
2          2     3.0
3          3     6.0
4          4     9.0
5          5    12.0
6          6    15.0
7          7    18.0
8          8    21.0
9          9    24.0
10        10    27.0
11        11    30.0
12        12    33.0
13        13    36.0
14        14    39.0

In [112]:
w=z.stack()
w.index.set_names(["letra","tipo"],inplace=True)
w

cuadrado     cube  cuboarea  normal      quad
letra tipo                                               
a                NaN      NaN      27.0     NaN       NaN
      area      9.00   27.000       NaN     3.0       NaN
      masa      9.00   27.000       NaN     3.0   81.0000
b                NaN      NaN      64.0     NaN       NaN
      area     16.00   64.000       NaN     4.0       NaN
c                NaN      NaN     125.0     NaN       NaN
      area     25.00  125.000       NaN     5.0       NaN
      masa     29.16  157.464       NaN     5.4  850.3056
d                NaN      NaN     216.0     NaN       NaN
      area     36.00  216.000       NaN     6.0       NaN
      masa      4.84   10.648       NaN     2.2   23.4256
f     masa      1.44    1.728       NaN     1.2    2.0736

In [116]:
w.groupby('tipo').max()

cuadrado     cube  cuboarea  normal      quad
tipo                                               
           NaN      NaN     216.0     NaN       NaN
area     36.00  216.000       NaN     6.0       NaN
masa     29.16  157.464       NaN     5.4  850.3056

In [117]:
w.groupby('letra').sum() #en general, .agg  

cuadrado     cube  cuboarea  normal      quad
letra                                               
a         18.00   54.000      27.0     6.0   81.0000
b         16.00   64.000      64.0     4.0    0.0000
c         54.16  282.464     125.0    10.4  850.3056
d         40.84  226.648     216.0     8.2   23.4256
f          1.44    1.728       0.0     1.2    2.0736

Y hasta aqui pandas. No le echamos un vistazo a dusk, que es la "version multinucleo" para paralelismo, ni a las matrices sparse

In [120]:
import numpy as np
x=np.random.rand(10,3)
x

array([[0.05420893, 0.30126577, 0.44431803],
       [0.72600163, 0.64744186, 0.66067369],
       [0.08152434, 0.77989282, 0.55435645],
       [0.59830048, 0.47984667, 0.08938903],
       [0.31702163, 0.41292299, 0.36779865],
       [0.33678712, 0.61805776, 0.16210618],
       [0.10650036, 0.20358716, 0.27925006],
       [0.97990879, 0.45137392, 0.7315017 ],
       [0.78112531, 0.39545111, 0.20291426],
       [0.8943749 , 0.26523865, 0.24117624]])

In [123]:
x.sum(axis=1)

array([0.79979274, 2.03411718, 1.41577361, 1.16753618, 1.09774327,
       1.11695106, 0.58933757, 2.16278441, 1.37949068, 1.40078979])

In [125]:
x.sum(axis=1) > 2

array([False,  True, False, False, False, False, False,  True, False,
       False])

In [126]:
x[ x.sum(axis=1) > 2  ]

array([[0.72600163, 0.64744186, 0.66067369],
       [0.97990879, 0.45137392, 0.7315017 ]])

In [127]:
!pip install pyspark

     |████████████████████████████████| 281.3 MB 28 kB/s              
  Preparing metadata (setup.py) ... done
     |████████████████████████████████| 198 kB 25.1 MB/s            
  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805912 sha256=4fa30f9d723d29b384e140d1ad836198643546dc37a2102759fa42211df9a7ad
  Stored in directory: /home/cursofis/.cache/pip/wheels/23/f6/d3/110e53bd43baeb8d7d38049733d48e39cbecd056f01dba7ee8
Successfully built pyspark


In [140]:
from pyspark import SparkContext

sc = SparkContext("local[*]")
 
def mult(x):
    y = np.array([2,3,4])
    return x*y
 
x = np.arange(10000)
rdistData = sc.parallelize(x) #r is for resilient
 
results = rdistData.map(mult).collect()

print(results[-10:])
print(rdistData.map(mult).take(5))
sc.stop()

[array([19980, 29970, 39960]), array([19982, 29973, 39964]), array([19984, 29976, 39968]), array([19986, 29979, 39972]), array([19988, 29982, 39976]), array([19990, 29985, 39980]), array([19992, 29988, 39984]), array([19994, 29991, 39988]), array([19996, 29994, 39992]), array([19998, 29997, 39996])]
[array([0, 0, 0]), array([2, 3, 4]), array([4, 6, 8]), array([ 6,  9, 12]), array([ 8, 12, 16])]


In [141]:
sc = SparkContext("local[*]")
 
def long(x):
    return np.arange(x)
 
x = np.arange(10000)
rdistData = sc.parallelize(x) #r is for resilient
  
print(rdistData.flatMap(long).take(50))
sc.stop()

[0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4]


In [148]:
#esto es intereante verlo en el htop
# 
sc = SparkContext("local[*]")
 
def long(x):
    return np.arange(x)
 
x = np.arange(100000)
rdistData = sc.parallelize(x) #r is for resilient
  
print(rdistData.flatMap(long).sum())
sc.stop()

166661666700000


In [153]:
#esto es intereante verlo en el htop
# 
sc.stop()
sc = SparkContext("local[*]")
 
def long(x):
    return np.arange(x)
 
x = np.arange(100000)
np.random.shuffle(x)
rdistData = sc.parallelize(x) #r is for resilient

#lo normal es hacer from operator import add
def add(x,y):
    return x+y
  
print(rdistData.flatMap(long).map(lambda x: x**2 ).reduce(add))
sc.stop()

8333000004166650000


In [149]:
#esto es intereante verlo en el htop
# 
sc.stop()
sc = SparkContext("local[*]")
 
def long(x):
    return np.arange(x)
 
x = np.arange(100000)
np.random.shuffle(x)
rdistData = sc.parallelize(x) #r is for resilient
  
print(rdistData.flatMap(long).sum())
sc.stop()

166661666700000


recapitulacion

Python:
listas, diccionarios, comprehension
modulos del sistema, io, graficas

numpy:
shape y tipo de un array, seleccion, slices
operaciones escalar-matrix, matriz-matrix y generalizadas. dot, inner...

numba: decorador njit

scipy:
integrate, stats, minimize

pandas:
Series, DataFrame, Index, rolling

importante moverse en la documentacion, no solo en stack overflow.
