In [53]:
L=8
import numpy as np
import scipy as sp

In [54]:
base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L]) #double es float64 en linux
sum(sum(sum(base)))

130816.0

In [55]:
#https://stackoverflow.com/questions/43086557/convolve2d-just-by-using-numpy
base.strides*2

(512, 64, 8, 512, 64, 8)

In [56]:
t=np.lib.stride_tricks.as_strided(base,(L-2,L-2,L-2,3,3,3),base.strides*2)
np.shape(t)

(6, 6, 6, 3, 3, 3)

In [57]:
t[0,0,0]

array([[[  0.,   1.,   2.],
        [  8.,   9.,  10.],
        [ 16.,  17.,  18.]],

       [[ 64.,  65.,  66.],
        [ 72.,  73.,  74.],
        [ 80.,  81.,  82.]],

       [[128., 129., 130.],
        [136., 137., 138.],
        [144., 145., 146.]]])

In [73]:
L=4
base=np.arange(L*L,dtype=np.double).reshape([L,L])
print(base)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [74]:
np.pad(base,1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.],
       [ 0.,  4.,  5.,  6.,  7.,  0.],
       [ 0.,  8.,  9., 10., 11.,  0.],
       [ 0., 12., 13., 14., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [75]:
np.pad(base,1,mode='wrap')

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [76]:
base.take(((2,4),(-1,1)),mode='wrap')

array([[ 2.,  4.],
       [15.,  1.]])

In [77]:
base.take([[0],[4]],mode='wrap')

array([[0.],
       [4.]])

In [78]:
x=np.pad(base,1,mode='wrap')

In [79]:
x

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [80]:
base[0,0]=48

In [81]:
base

array([[48.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [82]:
x

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [87]:
L=8
base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
basepad=np.pad(base,1,mode='wrap')
t=np.lib.stride_tricks.as_strided(np.pad(base,1,mode='wrap'),(L,L,L,3,3,3),basepad.strides*2)
t[0,0,0]

array([[[511., 504., 505.],
        [455., 448., 449.],
        [463., 456., 457.]],

       [[ 63.,  56.,  57.],
        [  7.,   0.,   1.],
        [ 15.,   8.,   9.]],

       [[127., 120., 121.],
        [ 71.,  64.,  65.],
        [ 79.,  72.,  73.]]])

In [89]:
L=4
base=np.arange(L*L,dtype=np.double).reshape([L,L])
basepad=np.pad(base,1,mode='wrap')
t=np.lib.stride_tricks.as_strided(np.pad(base,1,mode='wrap'),(L,L,3,3),basepad.strides*2)
t[0,0]

array([[15., 12., 13.],
       [ 3.,  0.,  1.],
       [ 7.,  4.,  5.]])

In [93]:
w=np.lib.stride_tricks.sliding_window_view(basepad,(3,3))
w.shape

(4, 4, 3, 3)

In [94]:
w[0,0]

array([[15., 12., 13.],
       [ 3.,  0.,  1.],
       [ 7.,  4.,  5.]])

In [99]:
np.sum(w,axis=(2,3))

array([[60., 57., 66., 63.],
       [48., 45., 54., 51.],
       [84., 81., 90., 87.],
       [72., 69., 78., 75.]])

In [101]:
sum(sum(w[0,0]))

60.0

In [103]:
np.shares_memory(w,basepad)

True

In [104]:
np.shares_memory(basepad,base)

False

In [108]:
rebase=basepad[1:-1,1:-1]
rebase

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [109]:
np.shares_memory(rebase,basepad)

True

In [110]:
"""see 
https://gist.github.com/slode/013331d35a816c864674b968ac9a9859
para una alternativa a np.pad()
"""

'see \nhttps://gist.github.com/slode/013331d35a816c864674b968ac9a9859\npara una alternativa a np.pad()\n'

In [111]:
basepad

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [112]:
basepad[0]=3434

In [113]:
basepad

array([[3.434e+03, 3.434e+03, 3.434e+03, 3.434e+03, 3.434e+03, 3.434e+03],
       [3.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 0.000e+00],
       [7.000e+00, 4.000e+00, 5.000e+00, 6.000e+00, 7.000e+00, 4.000e+00],
       [1.100e+01, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01, 8.000e+00],
       [1.500e+01, 1.200e+01, 1.300e+01, 1.400e+01, 1.500e+01, 1.200e+01],
       [3.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 0.000e+00]])

In [116]:
"""¿qué es mejor, pad, take con wrap, take con modulo...? """

'¿qué es mejor, pad, take con wrap, take con modulo...? '

In [ ]:
"""si el objetivo de la ventana es usar kernels de convolucion, scipy
tiene wrap
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html
"""