In [1]:
L=8
import numpy as np
import scipy as sp

In [2]:
base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L]) #double es float64 en linux
sum(sum(sum(base)))

130816.0

In [3]:
#https://stackoverflow.com/questions/43086557/convolve2d-just-by-using-numpy
base.strides*2

(512, 64, 8, 512, 64, 8)

In [4]:
t=np.lib.stride_tricks.as_strided(base,(L-2,L-2,L-2,3,3,3),base.strides*2)
np.shape(t)

(6, 6, 6, 3, 3, 3)

In [5]:
t[0,0,0]

array([[[  0.,   1.,   2.],
        [  8.,   9.,  10.],
        [ 16.,  17.,  18.]],

       [[ 64.,  65.,  66.],
        [ 72.,  73.,  74.],
        [ 80.,  81.,  82.]],

       [[128., 129., 130.],
        [136., 137., 138.],
        [144., 145., 146.]]])

In [6]:
L=4
base=np.arange(L*L,dtype=np.double).reshape([L,L])
print(base)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [7]:
np.pad(base,1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.],
       [ 0.,  4.,  5.,  6.,  7.,  0.],
       [ 0.,  8.,  9., 10., 11.,  0.],
       [ 0., 12., 13., 14., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
np.pad(base,1,mode='wrap')

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [9]:
base.take(((2,4),(-1,1)),mode='wrap')

array([[ 2.,  4.],
       [15.,  1.]])

In [10]:
base.take([[0],[4]],mode='wrap')

array([[0.],
       [4.]])

In [11]:
x=np.pad(base,1,mode='wrap')

In [12]:
x

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [13]:
base[0,0]=48

In [14]:
base

array([[48.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [15]:
x

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [16]:
L=8
base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
basepad=np.pad(base,1,mode='wrap')
t=np.lib.stride_tricks.as_strided(np.pad(base,1,mode='wrap'),(L,L,L,3,3,3),basepad.strides*2)
t[0,0,0]

array([[[511., 504., 505.],
        [455., 448., 449.],
        [463., 456., 457.]],

       [[ 63.,  56.,  57.],
        [  7.,   0.,   1.],
        [ 15.,   8.,   9.]],

       [[127., 120., 121.],
        [ 71.,  64.,  65.],
        [ 79.,  72.,  73.]]])

In [17]:
L=4
base=np.arange(L*L,dtype=np.double).reshape([L,L])
basepad=np.pad(base,1,mode='wrap')
t=np.lib.stride_tricks.as_strided(np.pad(base,1,mode='wrap'),(L,L,3,3),basepad.strides*2)
t[0,0]

array([[15., 12., 13.],
       [ 3.,  0.,  1.],
       [ 7.,  4.,  5.]])

In [18]:
w=np.lib.stride_tricks.sliding_window_view(basepad,(3,3))
w.shape

(4, 4, 3, 3)

In [19]:
w[0,0]

array([[15., 12., 13.],
       [ 3.,  0.,  1.],
       [ 7.,  4.,  5.]])

In [20]:
np.sum(w,axis=(2,3))

array([[60., 57., 66., 63.],
       [48., 45., 54., 51.],
       [84., 81., 90., 87.],
       [72., 69., 78., 75.]])

In [21]:
sum(sum(w[0,0]))

60.0

In [22]:
np.shares_memory(w,basepad)

True

In [23]:
np.shares_memory(basepad,base)

False

In [24]:
rebase=basepad[1:-1,1:-1]
rebase

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [25]:
np.shares_memory(rebase,basepad)

True

In [26]:
"""see 
https://gist.github.com/slode/013331d35a816c864674b968ac9a9859
para una alternativa a np.pad()
"""

'see \nhttps://gist.github.com/slode/013331d35a816c864674b968ac9a9859\npara una alternativa a np.pad()\n'

In [27]:
basepad

array([[15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.],
       [ 7.,  4.,  5.,  6.,  7.,  4.],
       [11.,  8.,  9., 10., 11.,  8.],
       [15., 12., 13., 14., 15., 12.],
       [ 3.,  0.,  1.,  2.,  3.,  0.]])

In [28]:
basepad[0]=3434

In [29]:
basepad

array([[3.434e+03, 3.434e+03, 3.434e+03, 3.434e+03, 3.434e+03, 3.434e+03],
       [3.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 0.000e+00],
       [7.000e+00, 4.000e+00, 5.000e+00, 6.000e+00, 7.000e+00, 4.000e+00],
       [1.100e+01, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01, 8.000e+00],
       [1.500e+01, 1.200e+01, 1.300e+01, 1.400e+01, 1.500e+01, 1.200e+01],
       [3.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 0.000e+00]])

In [30]:
"""¿qué es mejor, pad, take con wrap, take con modulo...? """

'¿qué es mejor, pad, take con wrap, take con modulo...? '

In [31]:
"""si el objetivo de la ventana es usar kernels de convolucion, scipy
tiene wrap
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html
"""
pesos=np.zeros((3,3,3))#,dtype=int)
pesos[1,2,1]=1
pesos[1,0,1]=1
pesos[0,1,1]=1
pesos[2,1,1]=1
pesos[1,1,0]=1
pesos[1,1,2]=1
pesos

array([[[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]],

       [[0., 1., 0.],
        [1., 0., 1.],
        [0., 1., 0.]],

       [[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]]])

In [32]:
%%timeit L=128; base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
basepad=np.pad(base,1,mode='wrap')
t=np.lib.stride_tricks.as_strided(basepad,(L,L,L,3,3,3),basepad.strides*2)
t=np.sum(t*pesos,axis=(3,4,5))


912 ms ± 2.34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%%timeit L=128; base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
basepad=np.pad(base,1,mode='wrap')
t=np.lib.stride_tricks.sliding_window_view(basepad,(3,3,3))
t=np.sum(t*pesos,axis=(3,4,5))

911 ms ± 6.51 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
import scipy.ndimage
L=128
base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L]);
t=sp.ndimage.convolve(base,pesos,mode='wrap')
t[0,0,0]

2113664.0

In [35]:
%%timeit L=128; base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
t=sp.ndimage.convolve(base,pesos,mode='wrap')

41.4 ms ± 283 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
t=sp.ndimage.convolve(base,pesos,mode='wrap')
t[0,0,0]

2113664.0

In [37]:
%%timeit L=128; base=np.arange(L*L*L,dtype=np.double).reshape([L,L,L])
t=sp.ndimage.correlate(base,pesos,mode='wrap')

40 ms ± 316 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [38]:
"""convolve/correlate gana por goleada a los stride_tricks, queda por ver si tambien gana a los indices a secas"""
"""(que se pueden hacer preindexando o calculando modulo"""
""

''

In [39]:
zplus=np.transpose(np.unravel_index(range(L*L*L),(L,L,L)))+(0,0,1)
zp=np.array([np.ravel_multi_index(i,(L,L,L),mode='wrap') for i in zplus])

In [40]:
%%timeit
t=base+base.take(zp).reshape((L,L,L))

21 ms ± 40.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
def move(L,step):
    unravel=np.transpose(np.unravel_index(range(L*L*L),(L,L,L)))+step
    return np.array([np.ravel_multi_index(i,(L,L,L),mode='wrap') for i in unravel])

In [42]:
xp=move(L,(1,0,0))
xm=move(L,(-1,0,0))
yp=move(L,(0,1,0))
ym=move(L,(0,-1,0))
zp=move(L,(0,0,1))
zm=move(L,(0,0,-1))

In [43]:
%%timeit
t=base+base.take(xp).reshape((L,L,L))+base.take(xm).reshape((L,L,L))+ \
base.take(yp).reshape((L,L,L))+base.take(ym).reshape((L,L,L))+ \
base.take(zp).reshape((L,L,L))+base.take(zm).reshape((L,L,L))

62.3 ms ± 370 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [44]:
%%timeit
t=base.reshape(L*L*L)+base.take(xp)+base.take(xm)+ \
base.take(yp)+base.take(ym)+ \
base.take(zp)+base.take(zm)

58.8 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%%timeit
t=(base.reshape(L*L*L)+base.take(xp)+base.take(xm)+ \
base.take(yp)+base.take(ym)+ \
base.take(zp)+base.take(zm)).reshape((L,L,L))

58.5 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [46]:
%%timeit
t=base+np.roll(base,+1,0)+np.roll(base,-1,0)+ \
    +np.roll(base,+1,1)+np.roll(base,-1,1) + \
    +np.roll(base,+1,2)+np.roll(base,-1,2)

58.9 ms ± 42.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [47]:
%%timeit t=np.zeros((L,L,L))
np.copyto(t,base)
for eje in 0,1,2:
    for d in -1,1:
        t+=np.roll(base,d,eje)

55.5 ms ± 179 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
%timeit t=np.zeros((L,L,L))
np.copyto(t,base)
for i in (xp,xm,yp,ym,zp,zm):
    t+=base.take(i).reshape((L,L,L))

2.38 ms ± 3.72 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [49]:
import numexpr #esto es para usar luego con evaluate

In [50]:
"""es sorprendente, pero parece que funciona"""
t=np.zeros((L,L,L))
np.copyto(t,base)
t*=1
for eje in 0,1,2:
    for d in -1,1:
        t+=np.roll(base,d,eje)
v=np.zeros((L,L,L))
np.copyto(v,base)
for i in (xp,xm,yp,ym,zp,zm):
    v+=base.take(i).reshape((L,L,L))
np.allclose(v,t)

True

In [51]:
%%timeit t=np.zeros((L,L,L))
np.copyto(t,base)
t[1:,:,:]+=base[:-1,:,:]
t[0,:,:]+=base[-1,:,:]
t[:-1,:,:]+=base[1:,:,:]
t[-1,:,:]+=base[0,:,:]

t[:,1:,:]+=base[:,:-1,:]
t[:,0,:]+=base[:,-1,:]
t[:,:-1,:]+=base[:,1:,:]
t[:,-1,:]+=base[:,0,:]

t[:,:,1:]+=base[:,:,:-1]
t[:,:,0]+=base[:,:,-1]
t[:,:,:-1]+=base[:,:,1:]
t[:,:,-1]+=base[:,:,0]

38.5 ms ± 712 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [52]:
def paso(x,y,z):#,base=None,step=None)
    return base[(x + 1) % L,y % L, z % L] #base[tuple((np.array([x,y,z])+step )%L )]
#print( paso(0,0,0,base=None,step=(0,-1,0)))
t=np.zeros((L,L,L))
np.copyto(t,base)
#for i in ((0,-1,0),(0,1,0)):
#    t+=np.fromfunction(paso,base=base,step=i,shape=(L,L,L))
t+=np.fromfunction(np.vectorize(paso),shape=(L,L,L),dtype=int)

In [53]:
""" For example, a[[0,0]] += 1 will only increment the first element once because of buffering, whereas add.at(a, [0,0], 1) will increment the first element twice."""

' For example, a[[0,0]] += 1 will only increment the first element once because of buffering, whereas add.at(a, [0,0], 1) will increment the first element twice.'

In [54]:
%%timeit
t=np.zeros((L,L,L))
np.copyto(t,base)
t+=np.fromfunction(np.vectorize(paso),shape=(L,L,L),dtype=int)

1.3 s ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
def paso(x,y,z, inc=(0,0,0)):
    return base[(x + inc[0] ) % L, (y + inc[1]) % L, (z+inc[2])%L ]
np.fromfunction(paso,shape=(L,L,L),inc=(0,0,-1),dtype=int).astype(int)[0]


array([[  127,     0,     1, ...,   124,   125,   126],
       [  255,   128,   129, ...,   252,   253,   254],
       [  383,   256,   257, ...,   380,   381,   382],
       ...,
       [16127, 16000, 16001, ..., 16124, 16125, 16126],
       [16255, 16128, 16129, ..., 16252, 16253, 16254],
       [16383, 16256, 16257, ..., 16380, 16381, 16382]])

In [56]:
%%timeit
t=np.zeros((L,L,L))
np.copyto(t,base)
t+=np.fromfunction(paso,shape=(L,L,L),inc=(0,0,-1),dtype=int)
t+=np.fromfunction(paso,shape=(L,L,L),inc=(0,0,1),dtype=int)
t+=np.fromfunction(paso,shape=(L,L,L),inc=(0,1,0),dtype=int)
t+=np.fromfunction(paso,shape=(L,L,L),inc=(0,-1,0),dtype=int)
t+=np.fromfunction(paso,shape=(L,L,L),inc=(1,0,0),dtype=int)
t+=np.fromfunction(paso,shape=(L,L,L),inc=(-1,0,0),dtype=int)

1 s ± 3.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [57]:
%%timeit x,y,z=np.indices((L,L,L))
t=np.zeros((L,L,L))
np.copyto(t,base)
t+=base[(x+1) %L,y,z]
t+=base[(x-1) %L,y,z]
t+=base[x,(y+1) %L,z]
t+=base[x,(y-1) %L,z]
t+=base[x,y,(z+1) %L]
t+=base[x,y,(z-1) %L] 


383 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [58]:
len(xp)

2097152

In [59]:
xp.itemsize

8

In [60]:
def move(L,step):
    unravel=np.transpose(np.unravel_index(range(L*L*L),(L,L,L)))+step
    return np.array([np.ravel_multi_index(i,(L,L,L),mode='wrap') for i in unravel], dtype=np.int32)

xp=move(L,(1,0,0))
xm=move(L,(-1,0,0))
yp=move(L,(0,1,0))
ym=move(L,(0,-1,0))
zp=move(L,(0,0,1))
zm=move(L,(0,0,-1))

In [61]:
xp.itemsize

4

In [62]:
%timeit t=np.zeros((L,L,L))
np.copyto(t,base)
for i in (xp,xm,yp,ym,zp,zm):
    t+=base.take(i).reshape((L,L,L))

2.35 ms ± 5.04 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [63]:
%timeit t=np.zeros((L,L,L))
np.copyto(t,base)
t+=base.take(xp).reshape((L,L,L))
t+=base.take(xm).reshape((L,L,L))
t+=base.take(yp).reshape((L,L,L))
t+=base.take(ym).reshape((L,L,L))
t+=base.take(zp).reshape((L,L,L))
t+=base.take(zm).reshape((L,L,L))

2.38 ms ± 3.81 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [64]:
base.size*xp.itemsize,base.size,2**16,2**32

(8388608, 2097152, 65536, 4294967296)

In [65]:
zm[:30]

array([127,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28], dtype=int32)

In [66]:
baseflat=base.flatten('K') #o C???

In [67]:
%%timeit t=np.zeros((L,L,L))
np.copyto(t,base)
t+=np.fromiter( (baseflat[i] for i in xp), dtype=float).reshape(L,L,L)
t+=np.fromiter( (baseflat[i] for i in xm), dtype=float).reshape(L,L,L)
t+=np.fromiter( (baseflat[i] for i in yp), dtype=float).reshape(L,L,L)
t+=np.fromiter( (baseflat[i] for i in ym), dtype=float).reshape(L,L,L)
t+=np.fromiter( (baseflat[i] for i in zp), dtype=float).reshape(L,L,L)
t+=np.fromiter( (baseflat[i] for i in zm), dtype=float).reshape(L,L,L)

3.63 s ± 4.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [68]:
%%timeit t=np.zeros(L*L*L)
np.copyto(t,base.reshape(L*L*L))
t+=np.fromiter( (baseflat[i] for i in xp), dtype=float)
t+=np.fromiter( (baseflat[i] for i in xm), dtype=float)
t+=np.fromiter( (baseflat[i] for i in yp), dtype=float)
t+=np.fromiter( (baseflat[i] for i in ym), dtype=float)
t+=np.fromiter( (baseflat[i] for i in zp), dtype=float)
t+=np.fromiter( (baseflat[i] for i in zm), dtype=float)

3.65 s ± 6.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [69]:
baseflat[zm][:10]

array([127.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.])

In [70]:
%%timeit t=np.zeros(L*L*L)
np.copyto(t,base.reshape(L*L*L))
t+=baseflat[xp]
t+=baseflat[xm]
t+=baseflat[yp]
t+=baseflat[ym]
t+=baseflat[zp]
t+=baseflat[zm]

70.1 ms ± 42.5 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [71]:
"""el problema es mas bien usar la stride para definir xp como iterador"""

'el problema es mas bien usar la stride para definir xp como iterador'

In [72]:
%%timeit t=np.zeros(L*L*L)
np.copyto(t,base.reshape(L*L*L))
t+=np.take(baseflat,np.fromiter((i for i in range(L*L*L)),dtype=np.int32))
t+=np.take(baseflat,np.fromiter((i for i in range(L*L*L)),dtype=np.int32))
t+=np.take(baseflat,np.fromiter((i for i in range(L*L*L)),dtype=np.int32))
t+=np.take(baseflat,np.fromiter((i for i in range(L*L*L)),dtype=np.int32))
t+=np.take(baseflat,np.fromiter((i for i in range(L*L*L)),dtype=np.int32))
t+=np.take(baseflat,np.fromiter((i for i in range(L*L*L)),dtype=np.int32))

1.22 s ± 48.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
