In [2]:
#https://stackoverflow.com/questions/35215161/most-efficient-way-to-map-function-over-numpy-array

import timeit
import numpy as np

f = lambda x: x ** 2
vf = np.vectorize(f)
uf=np.frompyfunc(f, 1, 1)

def test_direct(x, n):
    t = timeit.timeit(
        'f(x)',
        'from __main__ import x, f', number=n)
    print('direct: {0:.3f}'.format(t))

def test_vectorized(x, n):
    t = timeit.timeit(
        'vf(x)',
        'from __main__ import x, vf', number=n)
    print('vectorized: {0:.3f}'.format(t))

def test_ufunc(x, n):
    t = timeit.timeit(
        'uf(x)',
        'from __main__ import x, uf', number=n)
    print('universal: {0:.3f}'.format(t))

In [22]:
x = np.arange(1000)
n = 10000
test_direct(x, n)      # 0.007
test_vectorized(x, n)  # 0.945
test_ufunc(x,n)


direct: 0.041
vectorized: 4.855
universal: 4.084


In [6]:
x = np.arange(1000)
n = 10000
t = timeit.timeit(
        'for i in range(len(x)): x[i]=f(x[i])',
        'from __main__ import np, x, f', number=n)
print('t: {0:.3f}'.format(t))

t: 5.356


In [3]:
L=4
base=np.arange(L*L,dtype=np.double).reshape([L,L])
print(base)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [11]:
"""ravel y unravel son cosas que se hacen tipicamente en lattices cuando se usa C"""
np.unravel_index(6,base.shape)

(1, 2)

In [8]:
np.unravel_index(6,(3,3,3))

(0, 2, 0)

In [9]:
np.ravel_multi_index((1,2),base.shape)

6

In [10]:
np.ravel_multi_index((2,4),base.shape,mode='wrap')

8

In [14]:
np.unravel_index(range(27),(3,3,3))

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2]),
 array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1,
        1, 1, 2, 2, 2]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2, 0, 1, 2]))

In [16]:
[np.unravel_index(i,(3,3,3)) for i in range(27)]

[(0, 0, 0),
 (0, 0, 1),
 (0, 0, 2),
 (0, 1, 0),
 (0, 1, 1),
 (0, 1, 2),
 (0, 2, 0),
 (0, 2, 1),
 (0, 2, 2),
 (1, 0, 0),
 (1, 0, 1),
 (1, 0, 2),
 (1, 1, 0),
 (1, 1, 1),
 (1, 1, 2),
 (1, 2, 0),
 (1, 2, 1),
 (1, 2, 2),
 (2, 0, 0),
 (2, 0, 1),
 (2, 0, 2),
 (2, 1, 0),
 (2, 1, 1),
 (2, 1, 2),
 (2, 2, 0),
 (2, 2, 1),
 (2, 2, 2)]